### PR TITLE
Fetch more than 10 releases pages if from and to versions not reached

### LINKED ISSUE #741: Increase and enforce GitHub API release fetching quotas
### Describe the bug

I don't see a changelog after clicking on a legacy style URL to Octoclairvoyant.

### Give the steps to reproduce

1. Click on this link https://octoclairvoyant.vercel.app/comparator?repo=renovatebot%2Frenovate&to=24.22.3&from=23.95.0
2. No changelog

### What browsers are you seeing the problem on?

Bug is not about browser

### Have you thought of a possible solution?

No

### If you have thought of a solution, please tell us about it!

_No response_

### Do you want to help fix the bug?

No

### Is there anything else we need to know?

Maybe the version range is too big, and Octoclairvoyant craches or exceeds some GitHub API limit?

Or old style link not properly converted to new comparator slug?

I got the link from @Belco90 themselves, so I assume the link was good at the time it was posted. 😉 

Source of link: https://github.com/renovatebot/renovate/issues/8177#issuecomment-762352681

### PR DESCRIPTION
**Pull request by Belco90**
## Changes

- If `from` and `to` are available on first load of the page, ignore the 10 pages limit until releases matching both are found.

## Context

Closes #741

It takes a while to load tho, it has to paginate more than 40 pages!
CleanShot 2022-04-09 at 17 28 05

## Tests

I've checked my work by:

- [ ] Adding new tests or adjusting existing tests
- [X] Testing manually

I still need to add tests. I tried to do this in #767, but couldn't get them working as expected. Furthermore, I'll handle this in another PR, and also the GitHub API rate limit reached when trying to paginate more than 10 pages.

### CODE REVIEW

File: src/queries/release.tsx [hunk 1]
```diff
@@ -20,24 +28,42 @@ function useReleasesQuery(
...
+  const hasToVersion = !!toVersion
 
   return useQuery<ReleasesQueryResults, Error>(
     [QUERY_KEY, finalParams],
     async () => {
+      const releases: Array<Release> = []
       let paginationCount = 0
-      return octokit.paginate(
+
+      for await (const response of octokit.paginate.iterator(
```
Comment (Belco90) [inline src/queries/release.tsx:41]: Using `octokit.paginate.iterator` rather than `octokit.paginate` since has a better performance.

File: src/queries/release.tsx [hunk 2]
```diff
@@ -20,24 +28,42 @@ function useReleasesQuery(
...
-            done()
-          }
+        const isMaxAutoPaginationReached =
+          paginationCount === MAX_AUTO_PAGINATION
+        const lastReleaseFetched = response.data[response.data.length - 1]
+        const isFromReleaseFetched =
+          !hasFromVersion ||
+          semver.gte(fromVersion, lastReleaseFetched.tag_name)
+        const isToReleaseFetched =
+          !hasToVersion || semver.gte(toVersion, lastReleaseFetched.tag_name)
```
Comment (Belco90) [inline src/queries/release.tsx:55]: This is basically where the magic happens to check if both from and to versions have been fetched already.

**Comment by HonkingGoose** [comment]
I'm not sure how to test this. Can I test this on the Vercel preview, or do I need to have a token before I can test the behavior?

**Comment by Belco90** [comment]
- Go to the comparator in the Vercel preview
- Auth GitHub if you aren't still logged in
- Add `?repo=renovatebot%2Frenovate&to=24.22.3&from=23.95.0` to the url and access it
- Wait a bit to see how everything is loaded

**Comment by HonkingGoose** [comment]
I can't auth to GitHub from the Vercel preview. I'm seeing this error in the browser console after copy/pasting the query string and pressing <kbd>Enter</kbd>:

`HttpError: Only the first 1000 results are available.`

**Comment by Belco90** [comment]
> I can't auth to GitHub from the Vercel preview. I'm seeing this error in the browser console after copy/pasting the query string and pressing Enter:
> 
> `HttpError: Only the first 1000 results are available.`

That's because you aren't able to auth GitHub 😢 

You can auth it manually by copying your cookie from the prod platform into the preview one. Do you know how to do this?

**Comment by HonkingGoose** [comment]
> You can auth it manually by copying your cookie from the prod platform into the preview one. Do you know how to do this? I can assist you if not.

I don't know how to do this. Can you explain?

**Comment by Belco90** [comment]
> I don't know how to do this. Can you explain?

I recorded this short video to show you how to do so:

https://user-images.githubusercontent.com/2677072/163713510-73d17d47-68b2-4f8b-901c-df81fc620e89.mp4

**Review by HonkingGoose — APPROVED** [review]
Thank you for the "cookie copy" explanation. I've finally managed to test if this works. 🙈 😄 

I'm happy with the feature, but it takes a _long_ time to load the results, like you said.

Could we make a "progress bar" or even just show a "in-progress" spinner icon? Right now the user doesn't know that the site is "thinking", it takes so long that people will probably click away thinking the site has crashed. Might be worth tracking in a separate issue, so we're not doing too much in one PR. 😉

**Comment by Belco90** [comment]
Sure! IIRC there was a ticket for showing a spinner, but I need to double check this. Also, I'd like to check why the auth doesn't work for review envs.

**Comment by Belco90** [comment]
There wasn't a ticket for the loading spinner, so I've created #859
